name: robofitapp
description: A fitness app with personalized training plans, calendar, and video training.
version: 1.0.0+1

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  animate_do: ^3.1.2
  chewie: ^1.3.0
  flutter_cache_manager: ^3.4.1


  cupertino_icons: ^1.0.2


  # Logger for better debugging
  logger: ^2.5.0

  # Firebase dependencies
  firebase_core: ^3.9.0
  firebase_auth: ^5.3.4
  cloud_firestore: ^5.6.0
  firebase_storage: ^12.3.7

  # UI and helper packages
  table_calendar: ^3.0.9 # For calendar functionality
  provider: ^6.0.5       # For state management
  video_player: ^2.5.0   # For video playback
  flutter_localizations: # For localization support
    sdk: flutter

  # Other helpful packages
  shared_preferences: ^2.1.0 # For storing small amounts of data locally
  intl: ^0.19.0              # For formatting dates and numbers

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  
flutter:
  uses-material-design: true

  assets:
    - assets/videos/ # Folder for training videos
    - assets/images/ # Folder for images
    - assets/screenshots/

  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito-Regular.ttf
