# .github/workflows/firebase-hosting.yml
# This workflow deploys your project to Firebase Hosting when changes are pushed to the "main" branch.

name: Deploy to Firebase Hosting on Push
on:
  push:
    branches:
      - main  # Only triggers deployment for pushes to the "main" branch

permissions:
  contents: read  # Read permissions to fetch repository contents
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Deploy to Firebase Hosting
      - name: Deploy to Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}  # GitHub token for repository access
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_ROBOFITAPP_8B6EA }}  # Secret with Firebase Admin SDK service account JSON
          projectId: robofitapp-8b6ea  # Firebase project ID
